import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body className="bg-white dark:bg-black transition-colors duration-300">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />

            <main className="pt-32 pb-20">
              {children}
            </main>
            <Footer />

          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
